#!/usr/bin/env python3

# Usage: ./dummy_data_generator.py > file.sql
#  Note: this might only work with POSIX shells

# If you are using windows you can either copy paste the output into a file
# or reconsider using a better operating system.

from random import randint, uniform, choice

models_dict = {
    "Smartphone" : {
        "Apple" : ["iPhone SE", "iPhone 14"],
        "Samsung" : ["Galaxy S21", "Galaxy S7", "Galaxy A72"]
    },
    "TV" : {
        "LG" : ["B2 55\"", "C1 77\""]
    },
    "Laptop" : {
        "Apple" : ["MacBook Air 2022", "MacBook Pro 2020"],
        "Razer" : ["Razer Blade Stealth 2018", "Razer Blade 2020"]
    }
}

descriptions = [
    "Wooow look at this description!!",
    "Have a nice day!!",
    "This device does not work and will never work. Please do not waste your time on trying to fix this thing",
    "Soll ich die Beschreibungen auf Deutsch schreiben?",
    "Je m''appelle Paul",
    "J''adore le kebab",
    "Roma in Italiā est.",
    "These description where written while tracking my time.",
    "Das Gerät hat einen dubiosen Geruch; ich befürchte es funktioniert nicht mehr."
]

states = ["available", "reserved", "sold"]

# This will transform the weird hashmap into a list of tuples
# e.g. {"Smartphone" : {"Apple" : ["iPhone SE", "iPhone 14"} will become
#   [("Smartphone", "Apple", "iPhone SE"), ("Smartphone", "Apple", "iPhone 14")]
models = []
for typ, x in models_dict.items():
    for brand, y in x.items():
        for model in y:
            models.append((typ, brand, model))

# coordinates of vienna
# the backend (and this script) use WGS 84 (EPSG 4326) coordinates
longitude_r = (16.18, 16.58)
latitude_r = (48.11, 48.32)

user_id_r = (1, 20)
location_id_r = (1, 40)
collect_appointment_id_r = (1, 100)

num_items = 1000
num_models = len(models)

print("-- this was generated by the dummy_data_generator.py")
print("-- item models")

for i, (typ, brand, model) in enumerate(models):
    print(f"INSERT INTO item_model VALUES ({i+1}, '{typ}', '{brand}', '{model}');")

print("\n-- items")

for _ in range(num_items):
    model_id = randint(1, num_models)
    user_id = randint(*user_id_r)
    location_id = randint(*location_id_r)

    long = uniform(*longitude_r)
    lat = uniform(*latitude_r)
    description = choice(descriptions)

    status = choice(states)
    reservee = "NULL"
    if status != "available":
        # maybe check if it is not the same as user id
        reservee = randint(*user_id_r) 

    collect_appointment = "NULL"
    if status == "sold":
        collect_appointment = randint(*collect_appointment_id_r)

    print("INSERT INTO item (description, model_id, owner, location, status, reservee, collect_appointment, position) VALUES",
          f"('{description}', {model_id}, {user_id}, {location_id}, '{status}'::ITEM_STATUS, {reservee}, {collect_appointment},",
          f"ST_Point({long}, {lat}, 4326));")
