name: Rust

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "products/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: products

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
